// <auto-generated />
namespace TreinaWeb.MinhaApi.AcessoDados.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CriacaoTabelaAlunos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriacaoTabelaAlunos));
        
        string IMigrationMetadata.Id
        {
            get { return "201706131956126_CriacaoTabelaAlunos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
