// <auto-generated />
namespace TreinaWeb.MinhaAPI.AcessaDados.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class CriacaoTabelaAlunos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriacaoTabelaAlunos));
        
        string IMigrationMetadata.Id
        {
            get { return "202004121917401_CriacaoTabelaAlunos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
